### ISSUE TITLE
Add an image to the link from Home Page to Eating Snake

### ISSUE THREAD

**Issue by EugeneMab** [heyulan0112/Yulan-Website#13]

**Comment by heyulan0112** [comment]
complete.

**Comment by EugeneMab** [comment]
The image should be clickable
![image](https://user-images.githubusercontent.com/5307112/183144915-a5a11e27-f558-4634-96d8-6acc746297ad.png)

**Comment by EugeneMab** [comment]
@heyulan0112

**Comment by heyulan0112** [comment]
Complete, icon clickable.
